project_id = "dcqxqetlbgtaceyospij"

[functions.sleeper-lookup-user]
verify_jwt = true

[functions.sleeper-user-leagues]
verify_jwt = true

[functions.sleeper-league-snapshot]
verify_jwt = true

[functions.sleeper-import]
verify_jwt = true

[functions.sleeper-sync-players]
verify_jwt = true

[functions.sleeper-import-matchups]
verify_jwt = true
