project_id = "dcqxqetlbgtaceyospij"

[functions.sleeper-lookup-user]
verify_jwt = true

[functions.sleeper-user-leagues]
verify_jwt = true

[functions.sleeper-league-snapshot]
verify_jwt = true

[functions.sleeper-import]
verify_jwt = true

[functions.sleeper-sync-players]
verify_jwt = true

[functions.sleeper-import-matchups]
verify_jwt = true

[functions."ingest-projections"]
verify_jwt = false

[functions.ingest_projections]
enabled = true
verify_jwt = true
import_map = "./functions/ingest_projections/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ingest_projections/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ingest_projections/*.html" ]
