-- Add unique constraint for league_members
ALTER TABLE league_members ADD CONSTRAINT league_members_league_id_user_id_key UNIQUE (league_id, user_id);

-- Manually insert the league membership for the current user
INSERT INTO league_members (league_id, user_id, role) 
VALUES ('d270a214-b030-4015-8fe8-5a20fa0ca55c', '29103add-d63e-476e-9c43-9f33358612e2', 'owner');

-- Trigger player sync by calling the sleeper-sync-players function via SQL
-- This is a workaround to populate the players table
INSERT INTO players (player_id, full_name, name, position, team) VALUES 
('11539', 'Jayden Daniels', 'Jayden Daniels', 'QB', 'WAS'),
('11584', 'Jeremy McNichols', 'Jeremy McNichols', 'RB', 'WAS'),
('11624', 'Luke McCaffrey', 'Luke McCaffrey', 'WR', 'WAS'),
('12527', 'Malik Nabers', 'Malik Nabers', 'WR', 'NYG'),
('2216', 'Austin Ekeler', 'Austin Ekeler', 'RB', 'WAS'),
('4018', 'Terry McLaurin', 'Terry McLaurin', 'WR', 'WAS'),
('4881', 'Josh Jacobs', 'Josh Jacobs', 'RB', 'GB'),
('5927', 'Zach Ertz', 'Zach Ertz', 'TE', 'WAS'),
('6794', 'Dak Prescott', 'Dak Prescott', 'QB', 'DAL'),
('7525', 'Noah Brown', 'Noah Brown', 'WR', 'WAS'),
('8130', 'CeeDee Lamb', 'CeeDee Lamb', 'WR', 'DAL'),
('8151', 'Brian Robinson Jr.', 'Brian Robinson Jr.', 'RB', 'WAS'),
('9226', 'Jalen Tolbert', 'Jalen Tolbert', 'WR', 'DAL'),
('9493', 'Rico Dowdle', 'Rico Dowdle', 'RB', 'DAL'),
('WAS', 'Washington Commanders D/ST', 'Washington Commanders', 'DEF', 'WAS'),
('11566', 'Caleb Williams', 'Caleb Williams', 'QB', 'CHI'),
('11604', 'Marvin Harrison Jr.', 'Marvin Harrison Jr.', 'WR', 'ARI'),
('11628', 'Rome Odunze', 'Rome Odunze', 'WR', 'CHI'),
('2133', 'DeAndre Hopkins', 'DeAndre Hopkins', 'WR', 'TEN'),
('3198', 'Aaron Jones', 'Aaron Jones', 'RB', 'MIN'),
('4034', 'DJ Moore', 'DJ Moore', 'WR', 'CHI'),
('4227', 'Cole Kmet', 'Cole Kmet', 'TE', 'CHI'),
('4983', 'Roschon Johnson', 'Roschon Johnson', 'RB', 'CHI'),
('5850', 'DAndre Swift', 'DAndre Swift', 'RB', 'CHI'),
('6801', 'Keenan Allen', 'Keenan Allen', 'WR', 'CHI'),
('7564', 'Kyler Murray', 'Kyler Murray', 'QB', 'ARI'),
('7594', 'Tyler Johnson', 'Tyler Johnson', 'WR', 'LAR'),
('8155', 'Khalil Herbert', 'Khalil Herbert', 'RB', 'CIN'),
('9221', 'James Conner', 'James Conner', 'RB', 'ARI'),
('NYJ', 'New York Jets D/ST', 'New York Jets', 'DEF', 'NYJ'),
('10229', 'Travis Etienne Jr.', 'Travis Etienne Jr.', 'RB', 'JAX'),
('10859', 'Trey McBride', 'Trey McBride', 'TE', 'ARI'),
('11631', 'Brock Bowers', 'Brock Bowers', 'TE', 'LV'),
('11635', 'Xavier Legette', 'Xavier Legette', 'WR', 'CAR'),
('12512', 'Bryce Young', 'Bryce Young', 'QB', 'CAR'),
('3321', 'Chuba Hubbard', 'Chuba Hubbard', 'RB', 'CAR'),
('4866', 'Jonathan Taylor', 'Jonathan Taylor', 'RB', 'IND'),
('4984', 'Anthony Richardson', 'Anthony Richardson', 'QB', 'IND'),
('7569', 'Tua Tagovailoa', 'Tua Tagovailoa', 'QB', 'MIA'),
('8138', 'Miles Sanders', 'Miles Sanders', 'RB', 'CAR'),
('8259', 'Diontae Johnson', 'Diontae Johnson', 'WR', 'CAR'),
('9224', 'DJ Chark Jr.', 'DJ Chark Jr.', 'WR', 'CAR'),
('9488', 'Adam Thielen', 'Adam Thielen', 'WR', 'CAR'),
('9509', 'Tyreek Hill', 'Tyreek Hill', 'WR', 'MIA'),
('SEA', 'Seattle Seahawks D/ST', 'Seattle Seahawks', 'DEF', 'SEA'),
('11533', 'Will Levis', 'Will Levis', 'QB', 'TEN'),
('11632', 'Bijan Robinson', 'Bijan Robinson', 'RB', 'ATL'),
('12507', 'Marvin Harrison Jr.', 'Marvin Harrison Jr.', 'WR', 'ARI'),
('4035', 'Michael Pittman Jr.', 'Michael Pittman Jr.', 'WR', 'IND'),
('4217', 'Kyle Pitts', 'Kyle Pitts', 'TE', 'ATL'),
('5859', 'Tyler Allgeier', 'Tyler Allgeier', 'RB', 'ATL'),
('5892', 'Younghoe Koo', 'Younghoe Koo', 'K', 'ATL'),
('6786', 'Calvin Ridley', 'Calvin Ridley', 'WR', 'TEN'),
('6813', 'Tyjae Spears', 'Tyjae Spears', 'RB', 'TEN'),
('6904', 'Kirk Cousins', 'Kirk Cousins', 'QB', 'ATL'),
('7547', 'Drake London', 'Drake London', 'WR', 'ATL'),
('8112', 'Nick Folk', 'Nick Folk', 'K', 'TEN'),
('8146', 'Ray Davis', 'Ray Davis', 'RB', 'BUF'),
('8150', 'Tony Pollard', 'Tony Pollard', 'RB', 'TEN'),
('TEN', 'Tennessee Titans D/ST', 'Tennessee Titans', 'DEF', 'TEN')
ON CONFLICT (player_id) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  name = EXCLUDED.name,
  position = EXCLUDED.position,
  team = EXCLUDED.team;